server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${NAME}
    password: ${PASSWORD}
    driver-class-name: ${DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    upload-dir: uploads

logging:
  level:
    org.example.board: DEBUG
    org.springframework.web: DEBUG

app:
  image-base-url: ${BASE_URL}
  image-upload-dir: ${IMAGE_UPLOAD_DIR}
  image-download-url: ${IMAGE_DOWNLOAD_URL}